export function handleError(err: unknown) {
  console.error('Error:', err);
  process.exit(1);
}
